# Generated by Django 5.2.3 on 2025-06-10 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('caurse', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=100, unique=True)),
                ('date_admission', models.DateField()),
                ('date_valied', models.DateField()),
                ('parents_number', models.PositiveIntegerField()),
                ('student_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_paid', models.DateField()),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='ExamsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('scores', models.PositiveIntegerField()),
                ('date_exam', models.DateField()),
                ('students', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
