# Generated by Django 5.2.3 on 2025-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_students_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id_number',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
