# Generated by Django 5.2.3 on 2025-06-11 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_students_id_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('id_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('class_name', models.CharField(max_length=20)),
                ('parent_contact', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='examsreport',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.student'),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
