# Generated by Django 5.2.3 on 2025-06-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_student_alter_examsreport_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
